package com.sicredi.desafiovotacao.exception;

public class AssociadoNotFoundException extends RuntimeException{
    public AssociadoNotFoundException() {
        super();
    }
}
